### ISSUE TITLE
Enable usage of models trained on RoboLeague

### ISSUE THREAD

**Issue by bsati** [PG642/RLBot#1]
Implement a mechanism to load models trained with Unity ml-agents on RoboLeague.
The loaded model should be able to play in the RLBot environment. Further training on RLBot is not part of this feature.

**Comment by hndm** [comment]
An ONNX model can be loaded and used for inference but it is loaded every time the exercise is reseted. This leads to longer loading times for larger models. 
It should be availbale for all instances of the bot to reduce the overhead of repeatedly loading the model.
